### ISSUE TITLE
npm run build-browser does not work after typescript upgrade

### ISSUE THREAD

**Issue by mspanc** [radiokit/toolkit-js-playback#2]
```
$ npm run build-browser

> radiokit-toolkit-playback@1.0.9 build-browser /Users/marcin/aktivitis/radiokit/toolkit-js-playback
> webpack

Hash: 814a79b0f32b76100711
Version: webpack 1.14.0
Time: 650ms
    + 1 hidden modules

ERROR in ./lib/index.ts
Module build failed: Error: TypeScript compilation failed:
error TS18002: The 'files' list in config file 'tsconfig.json' is empty.
error TS18002: The 'files' list in config file 'tsconfig.json' is empty.

    at sendResult (/Users/marcin/aktivitis/radiokit/toolkit-js-playback/node_modules/webpack-typescript/lib/loadTypeScript.js:84:36)
    at Object.loadTypeScript [as default] (/Users/marcin/aktivitis/radiokit/toolkit-js-playback/node_modules/webpack-typescript/lib/loadTypeScript.js:23:5)
    at Object.module.exports (/Users/marcin/aktivitis/radiokit/toolkit-js-playback/node_modules/webpack-typescript/lib/index.js:3:29)
```

**Comment by mspanc** [comment]
Fixed in ea04792
